linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable-all: true
  disable:
    - prealloc
    - gosec
    - gochecknoglobals
    - dupl
    - gocyclo
    - unparam
    - scopelint
    - gocritic

run:
  skip-dirs:
    - vendor 

