language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  # Setup dependency management tool
- docker pull redislabs/rejson
- docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
- docker ps -a

install:
  - dep ensure

script:
  - go test -v .