language: go
go:
  - 1.10.x
  - 1.11.x

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services:
  - docker

before_install:
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - dep ensure
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --vendored-linters

script:
  - go test -v .
  - go test -covermode=count -coverprofile=profile.cov .
  - go vet -x .
  - staticcheck .
  - gometalinter --concurrency=4 --enable-gc --deadline=300s --disable-all --enable=deadcode --enable=errcheck --enable=goconst --enable=gofmt --enable=goimports --enable=golint --exclude=.pb.go --enable=gotype --enable=ineffassign --enable=interfacer --enable=lll --line-length=120 --enable=misspell --enable=structcheck --enable=unconvert --enable=unused --enable=varcheck --enable=vet --enable=maligned --vendor ./...

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

