go_import_path: github.com/nitishm/go-rejson

language: go
go:
  - 1.9.x
  - 1.10.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services:
  - docker

before_install:
  # Setup dependency management tool
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/golang/lint/golint                        # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -covermode=count -coverprofile=profile.cov .
  - go vet -x ./...
  - megacheck ./...
  - golint -set_exit_status $(go list ./...)

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false